# numpy

# Tüm modülü yükleme

In [3]:
import numpy as np # numpy modülünün tamamı yüklenir. 

In [4]:
np.sin(30)

-0.9880316240928618

In [5]:
np.sin(np.deg2rad(30))

0.49999999999999994

In [6]:
np.log10(10)

1.0

In [7]:
np.log(np.exp(1))

1.0

In [8]:
np.exp(1) # Euler sayısı 

2.718281828459045

# Belirli bir modülden sadece belilrli özellikleri yükleme

In [10]:
from numpy import sin, deg2rad # sadece bu iki fonksiyon yüklenir.

In [11]:
sin(deg2rad(30))

0.49999999999999994

In [12]:
np.sin(np.deg2rad(30)) ** 2 + np.cos(np.deg2rad(30)) ** 2 

1.0

## Matrix işlemleri 

In [14]:
data_list = [1,2,3]

In [15]:
data_list

[1, 2, 3]

In [16]:
import numpy as np

In [17]:
arr = np.array(data_list)

In [18]:
arr

array([1, 2, 3])

In [19]:
data_list2 = [[10,20,30],[40,50,60],[70,80,90]]

In [20]:
arr2 = np.array(data_list2)

In [21]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [22]:
arr3 = np.array([1,2,3,4,5])

In [23]:
arr3

array([1, 2, 3, 4, 5])

In [24]:
arr3[0]

1

In [25]:
arr3[4]

5

In [26]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [27]:
arr2[2,2] # 2. satır 2. sütun 

90

In [28]:
len(arr2)

3

In [29]:
type(arr2)

numpy.ndarray

In [30]:
np.arange(10,20) # 10'dan 20'ye kadar 20 dahil değil

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [32]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [35]:
np.zeros((5,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

aşağıdaki örnekte, 0 ile 100 arasını 4 eşit parçaya bölerek 5 tane değer tutmayı sağlıyor. 

In [38]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [39]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

# birim matris

In [41]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [42]:
np.random.randint(0,10)

6

In [43]:
np.random.randint(15) # (0,15) olarak algılar

13

In [44]:
np.random.randint(1, 20, 5) #1 ile 20 arasında 5 değer üretip np.array yaptı. 

array([ 5, 15,  4, 19,  6])

#### .randeom.rand metodu. tek parametre alır ve bu parametre değerine göre 0 ile 1 arası sayı üretir. 

In [46]:
np.random.rand(5) #0 ile 1 arasında 5 tane sayı üretti. 

array([0.80944022, 0.52285661, 0.71026687, 0.636184  , 0.85050475])

In [47]:
np.random.randn(5)

array([-0.53157847, -0.62760157, -1.03727145,  0.13970771, -0.17687475])

### .reshape metodu

In [49]:
arr = np.arange(25)

In [50]:
arr # dizi eleman sayısı ile matris botyutu tam uyuşmalı, eksik ya da fazla olamaz. 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
arr = np.random.randint(1,100,10)

In [53]:
arr

array([ 2, 24, 10, 51, 83, 43, 66, 89, 46, 38])

In [54]:
arr.max()

89

In [55]:
arr.min()

2

In [56]:
arr.sum() #arr elemanlarının toplamı 

452

In [57]:
arr.mean() # ortalaması 

45.2

In [58]:
arr.argmax()

7

In [59]:
arr.argmin()

0

# Determinant hesaplama

In [61]:
arr = np.random.randint(1, 100, 25)

In [62]:
arr

array([36, 95, 94, 55, 35, 29, 75, 69, 27, 75, 51, 67, 85, 52, 30, 62,  9,
       88, 53, 95, 50, 86, 96, 42, 88])

In [63]:
arrshape = arr.reshape(5,5)
arrshape

array([[36, 95, 94, 55, 35],
       [29, 75, 69, 27, 75],
       [51, 67, 85, 52, 30],
       [62,  9, 88, 53, 95],
       [50, 86, 96, 42, 88]])

In [64]:
np.linalg.det(arrshape)

-13610075.999999957

In [65]:
arr2 = np.array([[10,20],[1,2]])
arr2

array([[10, 20],
       [ 1,  2]])

In [66]:
np.linalg.det(arr2)

0.0

In [67]:
round(np.linalg.det(arr2))

0

# array lerin indekslenmesi ve parçalanması 

In [69]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
arr[2]

3

In [71]:
arr[1:4]

array([2, 3, 4])

In [72]:
arr[:4]

array([1, 2, 3, 4])

In [73]:
arr[::2]

array([1, 3, 5, 7, 9])

In [74]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
arr[:3]

array([1, 2, 3])

In [76]:
arr[:3] = 36

In [77]:
arr

array([36, 36, 36,  4,  5,  6,  7,  8,  9])

In [78]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
arr2 = arr
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
arr2[:3] = 100
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [81]:
arr #arr2' dek ideğişiklik arr' yi etkiledi. Sebebi bellekten okuma ! 

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

değişiklik olsun istemiyorsak copy metodu kullanılmalı 

In [83]:
arr= np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
arr2 = arr.copy()
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
arr2[:3] = 1000
arr2

array([1000, 1000, 1000,    4,    5,    6,    7,    8,    9])

In [86]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Çok boyutlu matrisler, parçalama, indeksleme

In [88]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [89]:
arr.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [90]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [91]:
arr = arr.reshape(5,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [92]:
arr[0,0]

1

In [93]:
arr[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

Virgünden öncesi satırlar için, tümünü aldık, virgülden sonrası sütunlar için 2' ye kadar 2 dahil değil. 

In [95]:
arr[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [96]:
arr[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# array'leri filtreleme

In [98]:
arr > 5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [99]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
booleanArray = arr > 5
booleanArray

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [101]:
arr[booleanArray]

array([ 6,  7,  8,  9, 10])

In [102]:
arr[arr>6]

array([ 7,  8,  9, 10])

# numpy arraylerinin temel operasyonları

In [104]:
arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([2,3,4,5,6,7])

In [105]:
arr1 + arr2

array([12, 23, 34, 45, 56, 67])

In [106]:
arr1 - arr2

array([ 8, 17, 26, 35, 44, 53])

In [107]:
arr1 * arr2 #inner product - skaler çarpma

array([ 20,  60, 120, 200, 300, 420])

In [108]:
arr1 + 10

array([20, 30, 40, 50, 60, 70])

In [109]:
arr2 - 4

array([-2, -1,  0,  1,  2,  3])

In [110]:
arr1 / 6

array([ 1.66666667,  3.33333333,  5.        ,  6.66666667,  8.33333333,
       10.        ])

### .sqrt()

In [113]:
np.sqrt(arr1)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781,
       7.74596669])

https://numpy.org/doc/1.24/reference/routines.linalg.html#module-numpy.linalg